stages:
  - build
  - test
build:
  stage: build
  image: "gradle:7.2.0-jdk17"
  script:
    - "mvn clean install -P qualification"
  tags:
    - docker2
  allow_failure: true

test:
  stage: test
  image: "gradle:7.2.0-jdk17"
  script:
    - mvn -B test
  tags:
    - docker2