stages:
  - build 
  - test

build:
  stage: build
  image: "openjdk:17-jdk-slim"
  script:
    - apt-get update
    - apt-get install -y maven
    - mvn clean install -P qualification
  tags:
    - docker2
  allow_failure: true

test:
  stage: test
  image: "openjdk:17-jdk-slim"
  script:
    - apt-get update
    - apt-get install -y maven
    - mvn -B test
  tags:
    - docker2
