version: '3'

services:
  postgres:
    command: [ "postgres" ]
    container_name: 'postgres_ili'
    image: 'postgres:latest'
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ili

  swagger:
    container_name: 'swagger'
    image: 'swaggerapi/swagger-ui'
    ports:
      - "80:8080"
    volumes:
      - ./src/main/webapp/doc:/docs
    environment:
      SWAGGER_JSON: /docs/swagger.yml